# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('AdmNo', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('Form_class', models.CharField(max_length=10)),
                ('Contact', models.CharField(max_length=25)),
                ('student_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somo.Grade')),
            ],
        ),
    ]
