# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('somo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_subject', models.CharField(max_length=25)),
                ('Marks', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='Contact',
        ),
        migrations.AddField(
            model_name='subject',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somo.Student'),
        ),
    ]
